image: snakemake/snakemake:stable

tasks:
  - name: Terminal 1
    init: |
      pip install beautifulsoup4
    command: |
      echo "PS1='\w\$ '" >> ~/.bashrc
      echo "*" > .gitignore
      conda init
      source ~/.bashrc
      clear
      conda activate snakemake
