image:
  file: snakemake/snakemake

tasks:
  - before: |
      pip install beautifulsoup4
  - command: |
      echo "PS1='\w\$ '" >> ~/.bashrc
      echo "*" > .gitignore
      conda init
      source ~/.bashrc
      clear
      conda activate snakemake
