image:
  file: snakemake/snakemake

tasks:
  - before: |
      pip install beautifulsoup4
  - init: |
      echo "*" > .gitignore
      conda init bash
      echo "conda activate snakemake" >> ~/.bashrc
