image: snakemake/snakemake

tasks:
  - name: main terminal
    before: |
      pip install beautifulsoup4
    command: |
      echo "*" > .gitignore
      conda init
      source ~/.bashrc
      clear
      conda activate snakemake