image: snakemake/snakemake

tasks:
  - name: main terminal
    command: |
      rm Dockerfile
      echo -e "# Snakemake\n\nYour gitpod workspace for the snakemake has been initialized. Now you can start with the [basic tutorial](https://snakemake.readthedocs.io/en/stable/tutorial/basics.html)." > README.md
      echo "PS1='\w\$ '" >> ~/.bashrc
      echo "*" > .gitignore
      conda init
      source ~/.bashrc
      clear
      conda activate snakemake
