name: Test container build

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: docker build .